name: SurfSense
package: community.lazycat.app.surfsense
version: 1.0.55
min_os_version: 1.3.8
description: 开源替代 NotebookLM、Perplexity 和 Glean
homepage: https://github.com/MODSetter/SurfSense
author: MODSetter
application:
  subdomain: surfsense
  background_task: true
  public_path:
    - /

  upstreams:
    - location: /
      backend: http://surfsense:3000/
    - location: /
      domain_prefix: backend
      backend: http://surfsense:8000/

services:
  surfsense:
    container_name: surfsense
    user: root
    #  ghcr.io/modsetter/surfsense:v1.0.55
    image: registry.lazycat.cloud/czyt/modsetter/surfsense:f0e4ccde2274c9ec
    binds:
      - /lzcapp/var/data:/data
    environment:
      - NEXT_PUBLIC_FASTAPI_BACKEND_URL=https://backend-{{.S.AppDomain}}
      - NEXT_PUBLIC_FASTAPI_BACKEND_AUTH_TYPE=LOCAL
      - AUTH_TYPE=LOCAL
      - REGISTRATION_ENABLED=true
    setup_script: |
      mkdir -p /data/postgres

locales:
  zh:
    name: "SurfSense"
    description: "开源替代 NotebookLM、Perplexity 和 Glean"
  en:
    name: "SurfSense"
    description: "Open source alternative to NotebookLM, Perplexity, and Glean"
